### ISSUE TITLE
Implementation for data obtained from NCBI

### ISSUE THREAD

**Issue by scottcain** [FAIR-bioHeaders/FHR-Specification#11]
Hi,

I would like to create yaml files for genome sequences obtained from NCBI but several items that are listed as required I have no idea how to include.  Here is sample yaml I created:

```
schema: https://raw.githubusercontent.com/FFRGS/FFRGS-Specification/main/ffrgs.json
schemaVersion: 1
taxon:
  name: Rattus norvegicus
  uri: https://identifiers.org/taxonomy:10116
genome: Rattus norvegicus
genomeSynonym:
  - R. norvegicus
  - Norway rat
version: mRatBN7.2
metadataAuthor:
- name: Scott Cain
  uri: https://orcid.org/0000-0003-0459-9607
assemblyAuthor:
- name: Wellcome Sanger Institute
  uri: https://www.sanger.ac.uk/
dateCreated: '2020-11-10'
instrument:
- PacBio Sequel
- 10X Genomics Chromium
- BioNano
- Arima Hi-C
documentation: 'Obtained from NCBI Genome Data Hub via the `datasets` command line tool: `datasets download genome accession GCF_015227675.2 --include genome --filename GCF_015227675.2.zip`'
relatedLink:
- https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_015227675.2/
checksum: abf4d503cb27458deed37ab0eb0b9b77
```
But missing from this sample are  "physicalSample" and  "location" which don't really make much sense in this context but are listed as required in the schema. I think that the above yaml probably performs the task required for FFRGS, which is to tell what the file is and where it came from.  I think this means that perhaps physicalSample and location shouldn't be required.
